#!/usr/bin/env node
/**
 * Kairo — First-Time Setup
 * Run: npm run setup
 * 
 * Asks for API keys, validates them, saves config.
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');
const os = require('os');

const KAIRO_DIR = path.join(os.homedir(), '.kairo');
const CONFIG_PATH = path.join(KAIRO_DIR, 'models.yml');

const PROVIDERS = [
  {
    name: 'nvidia',
    label: 'NVIDIA NIM',
    envKey: 'NVIDIA_API_KEY',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    model: 'nvidia/nemotron-3-ultra-550b-a55b',
    testModel: 'nvidia/nemotron-3-ultra-550b-a55b',
    getUrl: 'https://build.nvidia.com',
    hint: 'Get key from build.nvidia.com → any model → Get API Key',
  },
  {
    name: 'groq',
    label: 'Groq',
    envKey: 'GROQ_API_KEY',
    baseUrl: 'https://api.groq.com/openai/v1',
    model: 'openai/gpt-oss-20b',
    testModel: 'openai/gpt-oss-20b',
    getUrl: 'https://console.groq.com',
    hint: 'Get key from console.groq.com → API Keys',
  },
  {
    name: 'cerebras',
    label: 'Cerebras',
    envKey: 'CEREBRAS_API_KEY',
    baseUrl: 'https://api.cerebras.ai/v1',
    model: 'gpt-oss-120b',
    testModel: 'gpt-oss-120b',
    getUrl: 'https://cloud.cerebras.ai',
    hint: 'Get key from cloud.cerebras.ai → API Keys',
  },
];

function ask(question) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise(resolve => {
    rl.question(question, answer => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

async function validateKey(provider, key) {
  try {
    const resp = await fetch(`${provider.baseUrl}/chat/completions`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${key}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: provider.testModel,
        messages: [{ role: 'user', content: 'Say hi' }],
        max_tokens: 10,
        stream: false,
      }),
    });

    if (resp.ok) return { ok: true };
    const body = await resp.text();
    if (resp.status === 401 || resp.status === 403) return { ok: false, error: 'Invalid API key' };
    if (resp.status === 404) return { ok: true }; // model not found but key is valid
    return { ok: false, error: `HTTP ${resp.status}: ${body.slice(0, 100)}` };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

function generateConfig(keys) {
  let yaml = '# Kairo — Model Configuration\n';
  yaml += '# Generated by kairo setup\n\n';
  yaml += 'providers:\n';

  for (const provider of PROVIDERS) {
    const key = keys[provider.name];
    if (key) {
      yaml += `  ${provider.name}:\n`;
      yaml += `    apiKey: "${key}"\n`;
    }
  }

  yaml += '\n# Defaults\n';
  yaml += 'defaults:\n';
  yaml += '  provider: nvidia\n';
  yaml += '  model: nvidia/nemotron-3-ultra-550b-a55b\n';
  yaml += '  thinkingModel: nvidia/nemotron-3-ultra-550b-a55b\n';
  yaml += '  fastModel: groq/openai/gpt-oss-20b\n';

  return yaml;
}

async function main() {
  console.log('');
  console.log('  ╔══════════════════════════════════════╗');
  console.log('  ║         KAIRO SETUP                   ║');
  console.log('  ╚══════════════════════════════════════╝');
  console.log('');
  console.log('  Kairo needs at least one LLM provider to work.');
  console.log('  You can skip providers you don\'t have keys for.');
  console.log('');

  // Check existing config
  if (fs.existsSync(CONFIG_PATH)) {
    const overwrite = await ask(`  Config already exists at ${CONFIG_PATH}. Overwrite? (y/N): `);
    if (overwrite.toLowerCase() !== 'y') {
      console.log('  Keeping existing config. Done.');
      return;
    }
  }

  const keys = {};

  for (const provider of PROVIDERS) {
    // Check env var first
    const envKey = process.env[provider.envKey];
    if (envKey) {
      console.log(`  ${provider.label}: found ${provider.envKey} in environment`);
      const valid = await validateKey(provider, envKey);
      if (valid.ok) {
        console.log(`  ${provider.label}: ✅ validated`);
        keys[provider.name] = envKey;
      } else {
        console.log(`  ${provider.label}: ❌ ${valid.error}`);
      }
      continue;
    }

    console.log(`  ── ${provider.label} ──`);
    console.log(`  ${provider.hint}`);
    console.log(`  Get a key: ${provider.getUrl}`);

    const key = await ask(`  Enter ${provider.label} API key (or press Enter to skip): `);

    if (!key) {
      console.log(`  Skipped.`);
      continue;
    }

    console.log(`  Validating...`);
    const valid = await validateKey(provider, key);

    if (valid.ok) {
      console.log(`  ✅ ${provider.label} key validated`);
      keys[provider.name] = key;
    } else {
      console.log(`  ❌ ${valid.error}`);
      const retry = await ask(`  Try again? (y/N): `);
      if (retry.toLowerCase() === 'y') {
        const key2 = await ask(`  Enter ${provider.label} API key: `);
        if (key2) {
          const valid2 = await validateKey(provider, key2);
          if (valid2.ok) {
            console.log(`  ✅ ${provider.label} key validated`);
            keys[provider.name] = key2;
          } else {
            console.log(`  ❌ ${valid2.error}. Skipping.`);
          }
        }
      }
    }
  }

  const providerNames = Object.keys(keys);
  if (providerNames.length === 0) {
    console.log('');
    console.log('  No providers configured. Kairo needs at least one.');
    console.log('  Run `npm run setup` again when you have a key.');
    console.log('');
    return;
  }

  // Save config
  if (!fs.existsSync(KAIRO_DIR)) fs.mkdirSync(KAIRO_DIR, { recursive: true });
  const config = generateConfig(keys);
  fs.writeFileSync(CONFIG_PATH, config, 'utf-8');

  console.log('');
  console.log(`  ✅ Config saved to ${CONFIG_PATH}`);
  console.log(`  Providers: ${providerNames.join(', ')}`);
  console.log('');
  console.log('  Run kairo:');
  console.log('    node bin/kairo.js "your task here"');
  console.log('    node bin/kairo.js --swarm "complex task"');
  console.log('    node bin/kairo.js --smol "quick question"');
  console.log('');
}

main().catch(e => {
  console.error('Setup error:', e.message);
  process.exit(1);
});
